sudo: false
language: node_js
node_js:
  - "8.9"
cache:
  directories:
    - node_modules
env:
  global:
      - SAUCE_USERNAME: kriszyp
      - SAUCE_ACCESS_KEY: 468f7823-0321-4b0f-a3e3-3b25899c7c80
install:
  - travis_retry npm install
script: npm test
